# Generated by Django 4.1.5 on 2023-04-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_favorite'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='favorited_photos',
            field=models.ManyToManyField(related_name='favorited_users', through='webapp.Favorite', to='webapp.gallery', verbose_name='Избранные фото'),
        ),
    ]
